language: php

php:
  - 7.4
  - 7.3
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - vendor/bin/phpunit
  - sonar-scanner -Dsonar.projectKey=rogervila_relational-data-transfer-objects -Dsonar.sources=. -Dsonar.exclusions='vendor/**, tests/**' -Dsonar.php.tests.reportPath=junit-logfile.xml -Dsonar.php.coverage.reportPaths=clover.xml

addons:
  sonarcloud:
    organization: "rogervila-github"
    token:
      secure: "F/0Ob4pkuhC9iNo6foWq+7IL/y03C3NEX9nZ0v7dWFTaS+swcU4jXli9EjiLXnRomtb+KJrUtixsgfCbQFvYMObbK/gVO4KQ8BlYyMSUTxqlgnvI1jy2RwcScQXoQl0kCPtrO/ZVuJ8LRRiaPrWQW3qhCmSMfND/Y2g8u2WKLFu2tvaxNyevt5sBnAYjriE1HC4UwxChckaQcmQ/1Jsfb5aUiffMjBZIo8MKu5S0SttjlIxwKkou9rODQJmFZqQxtnJUhk6YuOHoktjW6ClnukTyO+xC4c6l+POp0BOE4wnHCHDBgyPT1G0oWhGAbddoNWdXRVj0wLVm0c7bfUOlKHkwl5F0zA73PiJDYZM/ozaRqK88kEmeUK4jU2ICCBY/UwDGUafejloRovFGzegKnAINHeJvyTic3bNYHn2JdFbtSqfbT4Q1dWW44ODQgbgpbQPbG5XZTLkggrZnQMEnkYd/Eetx7TiT8LZFs/2iMZlMn7nLDx5sCFIL+Mz4q0r2+xnNM/psAeLUp3VV4Y2FuPpXgwnGQ5FIMRRsfehZ3UE5aKmDN0R+AI/lbjWQZD5ehungmKLrfcyydrclYFRmPZFwJzuaq0j62Sb1mNfUg9SY6PzSOLKbHjnM7AxyOCKmpjgNQg+vZeB2Q9L1yPcBvdn1n/UqfBq2/rwRgpX00Sk="
